version: '3'
services:
    mongo-service:
        container_name: mongoContainer
        image: mongo
        ports: 
            - '27017:27017'
    node-service:
        container_name: nodeContainer
        restart: always
        build: .
        volumes:
            - .:/usr/src/app
            - node_modules
        ports:
            - '5000:5000'
        links:
            - mongo-service
