version: '3.5'
services:
    mongo-service:
        container_name: mongoContainer
        image: mongo
        # environment: 
            # MONGO_INITDB_ROOT_USERNAME: fegaris
            # MONGO_INITDB_ROOT_PASSWORD: fegarispass
        volumes:
            - ./mongoBackup:/mongoBackup
        command: mongorestore /mongoBackup/xoDb/*.bson
        ports: 
            - '27017:27017'
    node-service:
        container_name: nodeContainer
        restart: always
        build: .
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '5000:5000'
        links:
            - mongo-service
